### ISSUE TITLE
transaction service impl fails when auction has no winner.

### ISSUE THREAD

**Issue by ignasi35** [lagom/online-auction-java#103]
Current `master`, transaction service is subscribed to items topic.
Through that topic, an `AuctionFinished` event may be received. That event contains an `Optional<UUID> winner` but there may be auctions without winner.
Current code assumes the `Optional<UUID> winner` will always exist:

https://github.com/lagom/online-auction-java/blob/d1f8ce859e6e72ec417e6641acc33cd7e9a551c9/transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionServiceImpl.java#L31

When there's no winner that code crashes and subscription becomes useless.

**Comment by ignasi35** [comment]
The easiest way to have a no winner auction is to create an item on a 10 seconds auction, start the auction and let it finish without any bid.

**Comment by TimMoore** [comment]
Thanks for noticing, and sorry that I missed this.

@yg-apaza can you implement this fix, please? Be sure to add a test for this scenario... ideally add the test first to make sure it fails, then add the fix to make sure it fixes the test. 😄

**Comment by yg-apaza** [comment]
I fixed this in my huge PR :sweat_smile:
https://github.com/lagom/online-auction-java/blob/master/transaction-impl/src/main/java/com/example/auction/transaction/impl/TransactionServiceImpl.java#L35
I also added a integration test for this scenario: [`shouldNotCreateTransactionWithNoWinner`](https://github.com/lagom/online-auction-java/blob/master/transaction-impl/src/test/java/com/example/auction/transaction/impl/TransactionServiceImplIntegrationTest.java#L89)

Since it's hard to review this wasn't clear, so from now, I'll make smaller PRs

**Comment by TimMoore** [comment]
Oh, great! @ignasi35 could you have not had the latest `master` when you raised this?

**Comment by ignasi35** [comment]
I found that on my working branch to test lagom `1.4.0-SNAPSHOT` so I missed latest changes, yeah.
