### ISSUE TITLE
INSTRUCTIONS: create users

### ISSUE THREAD

**Issue by ignasi35** [lagom/online-auction-java#56]
Add inline instructions to create several users

**Comment by mehulsr** [comment]
Hi, my PR for this issue was merged. It is still open; does it need enhancement?

**Comment by TimMoore** [comment]
@mehulsr this is done now. Thanks for pointing it out.

For future reference, GitHub has a convention where if you add "Fixes #56" (or whatever the issue number is) to the description of the pull request, it will close the issue automatically when the pull request is merged. So it's better to use this convention rather than putting the issue number in the title of the pull request, where GitHub doesn't look for it.

Here's GitHub's documentation on how this works: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by mehulsr** [comment]
@TimMoore Okay, will keep this in mind for the next PR. Thanks!
