### ISSUE TITLE
User with username and password auth

### ISSUE THREAD

**Issue by lakhina** [lagom/online-auction-java#88]
As per email if we should provide username and password based login. We get two options for it.

- `Basic Auth` with saving username and password within `User` itself.
- `OAuth/OAuth2` by using any third party lib.

In basic auth  it will need every call to send username and password. That is generally not favourable though.

**Comment by lakhina** [comment]
@jroper Can you please guide on this.

**Comment by jroper** [comment]
Hi @lakhina,

I was more thinking of form based login with cookies. online-auction already uses cookie based authentication, so all that's needed is to provide a login page, where the user can enter their username and password, and that should submit it to a controller that checks that the password is correct, and if it is, set the current user in the session to be that user.

Currently we already have this:

https://github.com/lagom/online-auction-java/blob/master/web-gateway/app/controllers/Main.java#L65

That's how login currently works, you simply pass in the username, and it logs you in as that username, which is fine for using the drop down to log in as a particular user, and as mentioned we want to continue to support that for demo purposes (of course, in a real world app you would never support that). But we should add a new login action that takes a form that contains the username and password, check that the password is correct, and then if it is, set the user in the session, otherwise redirect back to the login page with an appropriate error.

**Comment by lakhina** [comment]
@jroper As per I can understand in this way we will we will not be authenticating each REST call we make to the server. Please correct me if I am wrong.

**Comment by ignasi35** [comment]
@lakhina we could if we add username/pwd on each call and create and setup new `HeaderFilters` for each service.

but that would be wrong. It is a bad idea to have a `username/password` pair in memory and send it on every request. Instead we should use some other form of authentication between services. But that is quite a big task.

This issue should only manage the authentication between the browser and the Play application. Once that is completed following @jroper's suggestion we can merge the PR and have a scenario where the perimeter application (play) is the only one requiring valid credentials and the internal communications (play-to-service or service-to-service) is considered trusted.

We can improve that later.

**Comment by lakhina** [comment]
@ignasi35 @ignasi35 As we want both type of signin options available I will add username/password option in tool if server is started with particular additional parameter. Will that be fine?

**Comment by lakhina** [comment]
if that env var is set to `true` we provide login screen and hide dropdown and vice versa

**Comment by ignasi35** [comment]
Prefer a settings over an ENV_VAR. Also, I think it's best if we use a `String` settings instead of a `Boolean`. That will give as more freedom of movement when we want to implement other login alternatives: `use-login="<[empty]|basic-form|OAUTH|fancy-stuff|other-fancy>"`

**Comment by rcavalcanti** [comment]
I personally don't think we should support both methods. I doubt if someone will configure it differently just for the sake of not using a login form. The intention is to have a demo app. 
(my 2 cents)

**Comment by ignasi35** [comment]
>  I personally don't think we should support both methods. I doubt if someone will configure it differently just for the sake of not using a login form. The intention is to have a demo app.(my 2 cents)

I've reconsidered. I agree to @renatocaval's statement.
